# Generated by Django 6.0.3 on 2026-03-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20260321_1735'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtickettype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),

        migrations.RunSQL(
            """
            UPDATE app_landingpage
            SET gallery_button_link = '3'
            WHERE gallery_button_link NOT GLOB '[0-9]*'
               OR gallery_button_link = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='landingpage',
            name='gallery_button_link',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),

        migrations.RunSQL(
            """
            UPDATE app_landingpage
            SET info_button_link = '13'
            WHERE info_button_link NOT GLOB '[0-9]*'
               OR info_button_link = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='landingpage',
            name='info_button_link',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),

        migrations.AlterField(
            model_name='productcustomfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='snipcartsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]